spring:
  application:
    name: cqrs_query

  data:
    mongodb:
      uri: "mongodb+srv://jhernandezm15_db_user:<db_password>@cluster0.d8hp5mg.mongodb.net/?appName=Cluster0"

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: restaurant-query
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "co.vinni.cqrs.dto"

server:
  port: 8622

kafka:
  topic:
    orders: order-events
    promotions: promotion-events
