spring.application.name=cqrs_query
server.port=8622

spring.data.mongodb.uri=mongodb+srv://jhernandezm15_db_user:1228@cluster0.d8hp5mg.mongodb.net/cqrs_query?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=cqrs_query

spring.logging.path=./logs
spring.logging.max.size=10MB
